function skip = should_skip(iyear, imonth)
    skip = (iyear == 13 && ismember(imonth, [9,10,11,12])) || ...
           (iyear == 14 && ismember(imonth, [1,2,3,4,5,9,10])) || ...
           (iyear == 15 && imonth == 12) || ...
           (iyear == 16 && imonth == 1) || ...
           (iyear == 19 && imonth == 10) || ...
           (iyear == 23 && imonth == 8) || ...
           (iyear == 12 && ismember(imonth, [1,2,3])) || ...
           (iyear == 1 && imonth == 1) || ...
           (iyear == 2 && ismember(imonth, [1,2,5])) || ...
           (iyear == 3 && ismember(imonth, [11,12])) || ...
           (iyear == 26 && imonth==2) || ...
           (iyear == 5 && ismember(imonth, [3,4,5,6,7]));
end
% (iyear == 8 && ismember(imonth, [10,11,12])) || ...
            % (iyear == 9 && ismember(imonth, [1,2,3,4,5,6])) || ...